version: "3.8"

x-env-keycloak:
  KEYCLOAK_USERNAME: &keycloak-username admin
  KEYCLOAK_PASSWORD: &keycloak-password admin

services:
  postgres:
    image: postgres:12.4
    healthcheck:
      test: su - postgres -c "psql -U postgres keycloak -c 'SELECT 1;' | grep '1 row' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycloak:
    build: keycloak-offline
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:8080/auth || exit 1
      interval: 10s
      timeout: 10s
      retries: 30
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: *keycloak-username
      KEYCLOAK_PASSWORD: *keycloak-password
      KEYCLOAK_LOGLEVEL: DEBUG
      #ROOT_LOGLEVEL: DEBUG
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres

  config-script:
    image: cfmanteiga/alpine-bash-curl-jq
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      KEYCLOAK_URI_BASE: http://keycloak:8080/auth
      KEYCLOAK_ADMIN_USERNAME: *keycloak-username
      KEYCLOAK_ADMIN_PASSWORD: *keycloak-password
    volumes:
      - ./keycloak-setup/realm-import.sh:/tmp/realm-import.sh
      - ./keycloak-setup/realm-export.json:/tmp/realm-export.json
    entrypoint: >
      sh -c "sh /tmp/realm-import.sh"
